version: "3"

services:
  react-app:
    image: "react-image-prod"
    container_name: "react-app-prod"
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_ENVINRONMENT=prod
    ports:
      - "8080:80"
