FROM node as build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_ENVINRONMENT
ENV REACT_APP_ENVINRONMENT=$REACT_APP_ENVINRONMENT
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html