FROM node as docker-build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
COPY ./yarn.lock /app/
RUN yarn
COPY . /app
ARG REACT_APP_ENVINRONMENT
ENV REACT_APP_ENVINRONMENT=$REACT_APP_ENVINRONMENT
RUN npm run build

FROM nginx:1.17.8-alpine
COPY --from=docker-build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf 
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]